name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    # Setup Node.js with cache
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: |
          backend/package-lock.json
          frontend/package-lock.json

    # Frontend Build
    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm ci

    - name: Build frontend
      working-directory: ./frontend
      run: npm run build --if-present

    - name: Test frontend
      working-directory: ./frontend
      run: npm test

    # Backend Build
    - name: Install backend dependencies
      working-directory: ./backend
      run: npm ci

    - name: Run backend dev
      working-directory: ./backend
      run: npm run dev --if-present

    - name: Test backend
      working-directory: ./backend
      run: npm test
